### ISSUE TITLE
Different folder for `niv init`

### ISSUE THREAD

**Issue by masaeedu** [nmattia/niv#102]
Might be a little late for this, but I'd prefer it if all my niv stuff went into `.niv` instead of `nix`. I was wondering if there's a way to make this configurable and still have everything work?

**Comment by nmattia** [comment]
Here’s something that could work well:

* by default niv looks first in `nix/`, then in `.niv/`
* on `niv init` you can specify `—sources-dir`

Thoughts ?

**Comment by masaeedu** [comment]
Maybe another alternative is that `niv init` works how it always did, but also creates a `.niv` config file in the root of the repo with all the default settings (e.g. `"sources-dir": "/nix"`). If you pass any flags or environment variables to override those settings, that's what shows up in the `.niv` config file on `niv init`. All the other commands simply refer to this config file to find the answers to all configurable questions.
