### ISSUE TITLE
GitHub errors are not reported to the user anymore

### ISSUE THREAD

**Issue by nmattia** [nmattia/niv#105]
All the user gets is this:

```
One or more packages failed to update:
niv: No rev: ParseError "Error in $: expected Vector a, encountered Object"
CallStack (from HasCallStack):
  error, called at src/Niv/GitHub.hs:136:19 in niv-0.1.1-JA4AHhZ4RkBKIGCn3c0RWr:Niv.GitHub
```

Probably a change to the `github` library.

**Comment by dysinger** [comment]
I'm also getting a regular

```
vega% niv add -b future hannesm/irmin 
Reading sources file
WARNING: Could not read from GitHub repo: hannesm/irmin
I assumed that your package was a GitHub repository. An error occurred while
gathering information from the repository. Check whether your package was added
correctly:

  niv show

If not, try re-adding it:

  niv drop <package>
  niv add <package-without-typo>

Make sure the repository exists.

(Error was: ParseError "Error in $: key \"description\" not present" )

One or more packages failed to update:
irmin: ParseError "Error in $: key \"description\" not present"
CallStack (from HasCallStack):
  error, called at src/Niv/GitHub.hs:43:9 in niv-0.1.1-JA4AHhZ4RkBKIGCn3c0RWr:Niv.GitHub
```

And the github library exists .... It seems random. I'll add the next library and it'll work.

**Comment by dysinger** [comment]
(And that repo has a description too)

**Comment by dysinger** [comment]
It seems like niv works for a half-dozen `add` operations and then it doesn't work anymore (for a period of time.) Maybe this is some absurdly low rate-limiting?

**Comment by dysinger** [comment]
Anyway. I'm chiming in on "it would be nice if --verbose said what was really happening with github"

**Comment by nmattia** [comment]
@dysinger indeed. Older versions of the `github` library would allow that, but right now it looks like it'll just print the error from `aeson`. I'm considering writing some lightweight GitHub bindings for niv, I've had quite a few issues with the `github` library already.
