### ISSUE TITLE
grouping / tagging of sources

### ISSUE THREAD

**Issue by hyperfekt** [nmattia/niv#114]
I'd love to use niv for updating my VSCode extensions, but would hate to have to enter `niv update [name]` for each of them every single time.

**Comment by nmattia** [comment]
I think this is a duplicate of #80 . Feel free to re-open if not.

**Comment by nmattia** [comment]
Oh and by the way, you can just run `niv update` and it'll update all the packages!

**Comment by hyperfekt** [comment]
Yeah, that's a duplicate! Must've missed it when looking through all the past issues. Thanks :)
