### ISSUE TITLE
 New update mechanism (#68) breaks conditional prefetch

### ISSUE THREAD

**Issue by leotaku** [nmattia/niv#115]
I recently noticed that the new update mechanism implemented in #68 removes the "only prefetch when url has changed" functionality introduced in #24. I personally think that this feature is pretty useful, so maybe we could have it be reintroduced?

PS: I am currently assuming that the feature hasn't been implemented in the never version, rather than it just being bugged and not working. I couldn't see any code related to it when skimming the source, but maybe this is really a bug.

**Comment by nmattia** [comment]
(Looks like I missed the notification, sorry for the delay)

Odd, that shouldn’t be the case. The whole point of the new update mechanism is to perform as little IO as necessary. Do you have some steps I can use to reproduce?

**Comment by leotaku** [comment]
Here are some simple steps to reproduce my issue (using the current master, but I have bisected through the git log and this should work with any commit after the new update mechanism):

* Go to a new folder
* `niv init` - Everything gets fetched (as it should)
* `niv update` - Everything gets fetched again
* `niv update` - Same as above

**Comment by nmattia** [comment]
Woops, dropped the ball on this. You're right, there's something wrong. Looking.

**Comment by nmattia** [comment]
@leotaku can you try https://github.com/nmattia/niv/tree/nm-too-many-fetches ( #120 ) ?

**Comment by leotaku** [comment]
Thank you! I tested using the pull and everything seems to be working now!
