### ISSUE TITLE
Optional config.nix collocated with sources.nix

### ISSUE THREAD

**Issue by nmattia** [nmattia/niv#116]
It occurred to me that we could have an optional `config.nix` file located at `./config.nix` where `./.` is the directory containing the `sources.nix`.

The configuration could specify which packages use builtin fetchers ( #46 ) and specify the relative location of the `sources.json` (#102 ).

Because `sources.nix` is the only file the user has to care about, the UX wouldn't be affected: the `config.nix` would live in the same directory, but `sources.json` could live anywhere. We can trivially implement this using `pathExists` to check whether `config.nix` exists or not, without breaking backwards compatibility.

Thoughts @michaelpj @nlewo  @masaeedu ?

**Comment by michaelpj** [comment]
I'm not sure I understand why this helps?
- What's the advantage of specifying the fetcher in `config.nix` instead of `sources.json`?
- If you want to move `sources.json` currently, you can just move `sources.nix` along with it. If I wanted to do this "indirectly" I could just write my own tiny nix file that imports `sources.nix` from wherever it actually is.

**Comment by nmattia** [comment]
> What's the advantage of specifying the fetcher in config.nix instead of sources.json?

I think it’s a better separation of concerns, and prevents us from having to duplicate every `type` with a `builtin-` version.

> If you want to move sources.json currently, you can just move sources.nix along with it. If I wanted to do this "indirectly" I could just write my own tiny nix file that imports sources.nix from wherever it actually is.

Agreed, but moving the `sources.nix` breaks `niv`’s assumption that it lives in `nix/`.

**Comment by michaelpj** [comment]
> I think it’s a better separation of concerns, and prevents us from having to duplicate every type with a builtin- version.

But that's not an orthogonal factor. Not every fetcher has a builtin version, only the small list of ones implemented in Nix. Imagine we add all the fetchers in `pkgs/build-support`, only three or so of them would have builtin versions. So I think it's simpler to just think of the builtin ones as additional fetchers that happen to behave similarly.

> Agreed, but moving the sources.nix breaks niv’s assumption that it lives in nix/.

Ah right, it updates it too. Fair point. Although I slightly wonder if this is a solution in search of a problem (does anyone have this problem?).

**Comment by nmattia** [comment]
Closing, we're going with #134
