### ISSUE TITLE
Error during niv add

### ISSUE THREAD

**Issue by jfroche** [nmattia/niv#122]
Hello,

I face this error when I don't provide the revision:

```
$ niv add terraform-providers/terraform-provider-vault                                                                       
Reading sources file
One or more packages failed to update:
terraform-provider-vault: No rev: ParseError "Error in $[24].committer: key \"id\" not present"
CallStack (from HasCallStack):
  error, called at src/Niv/GitHub.hs:136:19 in niv-0.1.1-JA4AHhZ4RkBKIGCn3c0RWr:Niv.GitHub
```

**Comment by nmattia** [comment]
Thanks for the report! Yep, I can reproduce. With curl as well:

> curl -L api.github.com/repos/terraform-providers/terraform-provider-vault/commits | jq '.[] | .committer'

Some of the committers are `null`, which seems to throw off the Haskell github library. I'll need to work around that, I'll keep you posted.
