### ISSUE TITLE
Fetch via git:// does not work

### ISSUE THREAD

**Issue by tfc** [nmattia/niv#130]
Hi there,

i am getting the following error:

```bash
$ niv add ipxe -t git://git.ipxe.org/ipxe.git
Adding package ipxe
Reading sources file
Could not read the output of 'nix-prefetch-url'. This is a bug. Please create a
ticket:

https://github.com/nmattia/niv/issues/new

Thanks! I'll buy you a beer.
stdout:

stderr:
warning: unable to download 'git://git.ipxe.org/ipxe.git': Unsupported protocol (1); retrying in 281 ms
warning: unable to download 'git://git.ipxe.org/ipxe.git': Unsupported protocol (1); retrying in 658 ms
warning: unable to download 'git://git.ipxe.org/ipxe.git': Unsupported protocol (1); retrying in 1383 ms
warning: unable to download 'git://git.ipxe.org/ipxe.git': Unsupported protocol (1); retrying in 2547 ms
error: unable to download 'git://git.ipxe.org/ipxe.git': Unsupported protocol (1)


One or more packages failed to update:
ipxe: ExitFailure 1

ERROR: ExitFailure 1
```

When i omit the `git://` prefix, it fetches via http and that doesn't work as the store output path just contains HTML of the gitweb's page.

Did i do it even right or is that a bug?

**Comment by nmattia** [comment]
Hi there!

Unfortunately `niv` doesn't handle git sources right now, it's tracked in #58 . I'm working on this right now, should hopefully be ready soon!

For context, the `-t` template should render to a URL. `niv` should probably emit a warning if that's not the case.

**Comment by nmattia** [comment]
You can now do the following:

```
$ niv add git git://git.ipxe.org/ipxe.git --ref master
Adding package ipxe
  Writing new sources file
Done: Adding package ipxe
```

The `niv add git` subcommand is still experimental. Looks like fetching the default branch doesn't always work, I created a ticket: https://github.com/nmattia/niv/issues/158
