### ISSUE TITLE
Uncondtional evaluation of `<nixpkgs>` causes lorri to watch nixpkgs even if it's not used

### ISSUE THREAD

**Issue by michaelpj** [nmattia/niv#143]
A multi-tool interaction, but an interesting one. See https://github.com/target/lorri/issues/176 for context.

Essentially, [this line](https://github.com/nmattia/niv/blob/master/nix/sources.nix#L52) means we unconditionally evaluate `<nixpkgs>`, which makes lorri watch it even if we don't use it in the end. 

I propose that we flip the logic: try the `nixpkgs` defined in the sources first, and only if there isn't one try using `<nixpkgs>`.

**Comment by michaelpj** [comment]
I can make a patch for this if we agree on the approach.

**Comment by nmattia** [comment]
@michaelpj I think the easiest fix right now would be to replace the `tryEval` hack with this:

> builtins.any (x: x.prefix == "nixpkgs") builtins.nixPath

**Comment by nmattia** [comment]
Basically:

``` diff
diff --git a/nix/sources.nix b/nix/sources.nix
index 2de89a6..86ab9d9 100644
--- a/nix/sources.nix
+++ b/nix/sources.nix
@@ -51,7 +51,7 @@ with rec

   hasNixpkgsPath = (builtins.tryEval <nixpkgs>).success;
   hasThisAsNixpkgsPath =
-    (builtins.tryEval <nixpkgs>).success && <nixpkgs> == ./.;
+    builtins.any (x: x.prefix == "nixpkgs") builtins.nixPath;

   sources = builtins.fromJSON (builtins.readFile ./sources.json);

```

**Comment by michaelpj** [comment]
Gross, but it would probably work. I think using the one in sources by default is better behaviour anyway, since it keeps things hermetic unless it can't, but this is a smaller change.
