### ISSUE TITLE
Make path to nix/* configurable

### ISSUE THREAD

**Issue by cprussin** [nmattia/niv#148]
I have some projects where I keep my nix files elsewhere from `nix/*` and it would be really nice to move the `nix/sources.json` and `nix/sources.nix` files elsewhere.  Probably just making the `nix/` prefix configurable somehow would be awesome. 
 Would that be a large ask?

**Comment by nmattia** [comment]
The implementation wouldn't be difficult. However it's unclear how this should be set:

* Should there be heuristics for figuring out where the `sources.json` is when running `niv`?
* Should there be a configuration file in the repository?
* Should all calls to `niv` have a flag that specifies the path?

Happy to get some feedback. This might interest you as well: https://github.com/nmattia/niv/issues/102

**Comment by cprussin** [comment]
I think a config file would be great, but cli flags are probably plenty (after all this is nix, I can just `wrapProgram` in my `shell.nix` to get my default arguments in, and it's not ultimately much of a different experience than having a config file)
