### ISSUE TITLE
[Init] nix-prefetch-url doesn't follow redirect

### ISSUE THREAD

**Issue by brano543** [nmattia/niv#162]
Hello,

am I the only one who can't successfully get nixpkgs through 'niv init' command?  The error is
`error: unable to download 'https://github.com/NixOS/nixpkgs-channels/archive/5f7eae4bbb15ce7fa4da1984fd6ba5be7af50952.tar.gz': HTTP error 200 (curl error: Failure when receiving data from the peer)`

The problem seems to be that nix-prefetch-url doesn't seem to follow redirect. I tested it with curl.
```
curl https://github.com/NixOS/nixpkgs-channels/archive/5f7eae4bbb15ce7fa4da1984fd6ba5be7af50952.tar.gz
<html><body>You are being <a href="https://codeload.github.com/NixOS/nixpkgs-channels/tar.gz/5f7eae4bbb15ce7fa4da1984fd6ba5be7af50952">redirected</a>.</body></html>
```

**Comment by brano543** [comment]
The only way I am able to workaround the issue is to let 'niv init' fail and then run

`niv add nixpkgs -v 19.09 -t 'https://codeload.github.com/NixOS/nixpkgs/tar.gz/<version>'`
which writes correct entry to sources.json as:
```
 "nixpkgs": {
        "sha256": "113zmdky5q0gvc1z2p6171a7h5p32b6rfac8qagxqd80s7xf68xc",
        "type": "file",
        "url": "https://codeload.github.com/NixOS/nixpkgs/tar.gz/19.09",
        "url_template": "https://codeload.github.com/NixOS/nixpkgs/tar.gz/<version>",
        "version": "19.09"
    }
```

**Comment by nmattia** [comment]
That's really odd. Can you run `nix --version`, `nix-build --version` and `nix-prefetch-url --version`?

**Comment by brano543** [comment]
I have version 2.3.1. I think it has something to do with Niv, because normally I can install packages without problem (through nix-env -i). Also the above command works only sometimes while direct curl call always succeeds. Just to note I am behind proxy server.

**Comment by nmattia** [comment]
Ok, maybe that's the issue. When I run it I get an HTTP 302 whereas you seem to get 200, in spite of the redirect message.

**Comment by brano543** [comment]
I am getting 302 response with curl, but the nix-prefetch-url doesn't get it that it should redirect.

**Comment by brano543** [comment]
I was able to figure it out. It is not enough to have just http_proxy and https_proxy variables being set up. One also needs to configure Git proxy as follows
```
git config --global http.proxy <address:port>
git config --global https.proxy <address:port>
```
in order for nix-prefetch-url to work correctly. 

I have one more question though. I am new to Nix and I am not sure that I get it on how to use this library. Let's assume an example of a existing Nix expression, eg. https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/libosmium/default.nix. 

If my understanding is correct, then Niv will just fetch the source files for the library. What I don't understand is this example you provide on main page
```
{ sources ? import ./sources.nix }:     # import the sources
with
  { overlay = _: pkgs:
      { niv = import sources.niv {};    # use the sources :)
      };
  };
import sources.nixpkgs                  # and use them again!
  { overlays = [ overlay ] ; config = {}; } 
```
How is that supposed to work if one does not provide a derivation which overrides existing package, like this example https://nixos.wiki/wiki/Overlays.

Instead I think that your library is intended to be used like this. I am following the same example from above.
```
{ stdenv, fetchFromGitHub, cmake, protozero, expat, zlib, bzip2, boost, sources ? import ./nix/sources.nix  }:

stdenv.mkDerivation rec {
  pname = "libosmium";
  src = sources.libosmium;

  nativeBuildInputs = [ cmake ];
  buildInputs = [ protozero zlib bzip2 expat boost ];


  meta = with stdenv.lib; {
    description = "Fast and flexible C++ library for working with OpenStreetMap data";
    homepage = "https://osmcode.org/libosmium/";
    license = licenses.boost;
    maintainers = with maintainers; [ das-g ];
  };
}
```

**Comment by nmattia** [comment]
>  One also needs to configure Git proxy as follows [...] in order for nix-prefetch-url to work correctly.

That is very odd, I would raise an issue on https://github.com/NixOS/nixpkgs.

>  I am new to Nix

Welcome! Please speak up if anything feels difficult. You can ask for help on https://discourse.nixos.org/, or IRC, or here.

> Instead I think that your library is intended to be used like this [...]

Yes, that's correct. There are many ways to use niv, and some examples should be provided.

https://github.com/nmattia/niv/issues/166

P.S.: In your example, the `description` and `homepage` can respectively be set to `sources.libosmium.description` and `sources.libosmium.homepage`, provided `libosmium` was added from GitHub:

``` nix
{ ... } :

stdenv.mkDerivation rec {
  ...
  meta = ... { 
    inherit (sources.libosmium) description homepage;
  };
}
```

**Comment by nmattia** [comment]
Closing as the nix-prefetch-url issue seems to have been solved. Feel free to re-open if you have more questions!
