### ISSUE TITLE
a way to use a different directory than "nix"

### ISSUE THREAD

**Issue by shajra** [nmattia/niv#172]
Hi!

I like `niv` quite a lot, but as far as I can tell, the current working directory needs to be right below a directory named "nix."  If I'm wrong, then I missed something, someone can tell me show me what I'm looking for, and we can close the ticket.

Otherwise, I think it would be nicer for scripting to be able to specify with a `--target DIR` flag the directory where `sources.json` and `sources.nix` are to managed, with the backwards-compatible default of `./nix`.

It's also kind of nicer for projects that are mostly Nix files anyway, because separating the "sources.*" files into their own "nix" directory doesn't make much sense.  Specifically, I've got a Nix tutorial project where I'm trying to be very conscientious of which files are where for pedagogical/beginner-friendly reasons.

So I'm hoping this feature request isn't objectionable.  I know enough Haskell to implement it.  I just am knocking out a few other things first.  But if someone beats me to implementing this, I won't complain :smiley:.

**Comment by nmattia** [comment]
It's _somewhat_ possible currently, you can specify `--sources-json` (which is a file as opposed to a directory). See also https://github.com/nmattia/niv/pull/133 for directory support. I didn't get a chance to do much coding over the holidays, but I'll get back to that PR asap!

**Comment by nmattia** [comment]
(feel free to re-open if https://github.com/nmattia/niv/pull/133 is not exactly what you're looking for!)
