### ISSUE TITLE
Why not in nixpkgs?

### ISSUE THREAD

**Issue by novoxudonoser** [nmattia/niv#177]
As I see `niv` tool don't present in nixpkgs and needs to be installed from the tarball.  I guess there is some reason for this. What is it?

**Comment by nmattia** [comment]
It should be available in nixpkgs; it's definitely in nixpkgs master:

```
nix-repl> sources = import ./nix/sources.nix

nix-repl> (import sources.nixpkgs {}).niv.version
"0.2.9"

nix-repl> sources.nixpkgs.rev
"5239b328f8796192db8f8516fc5dc2d270c8ab10"

nix-repl> sources.nixpkgs.branch
"master"
```

I'm not sure how long it takes to get into e.g. `release-19.09` et al.

**Comment by zimbatm** [comment]
maybe it's because the README installation section doesn't talk about it

**Comment by novoxudonoser** [comment]
I am not sure but I searched in https://nixos.org/nixos/packages.html?channel=nixos-19.09 and did not find anything (maybe I just was not accurate). Now I searched again and found `nix-env -iA nixos.haskellPackages.niv`, @nmattia maybe update readme?

**Comment by nmattia** [comment]
Updated the README, thanks for the suggestion!
