### ISSUE TITLE
Too fat dependencies (2.4GB)

### ISSUE THREAD

**Issue by novoxudonoser** [nmattia/niv#178]
On the fresh installation:
```
these derivations will be built:
  /nix/store/nysjh1jxrmi90vwdlda5qdfhzk2b84np-remove-references-to.drv
  /nix/store/nfcc25jn4dv2v998gr7jgcw8mdcnr8wp-niv-0.2.11.drv
these paths will be fetched (184.45 MiB download, 2412.51 MiB unpacked):
```
I checked the actual disc size, and yes, it has grown to 2.4GB. Is there anything to do about this? I guess there should be any possibilities to reduce unpacked dependency size.

**Comment by nmattia** [comment]
ok, this is definitely a bug. I'm guessing it's pulling in GHC as well, I'll have a look.
