### ISSUE TITLE
`niv init --bare`

### ISSUE THREAD

**Issue by zimbatm** [nmattia/niv#18]
The `niv init` currently creates a bit too many files for my liking. Currently `niv init` is playing two roles:

* install the `nix/source.{nix,json}` files which are indispensable, need to be at that location and managed by `niv`.
* populate the folder with some default files.

By separating those two it might be clearer what files niv really needs when it's generated.

The default generated files are also not quite to my personal preferences. My default template would be:
* the `nix/source.{nix,json}` files
* a `shell.nix` that loads source.nixpkgs
* a `.envrc` with `use nix`

I can easily expand that later if needed.

So I propose:
* `niv init --bare` only creates the bare-minimum files
* some way to override the default template, maybe use the content of `~/.config/niv/template` if it exists?

**Comment by roberth** [comment]
I'd prefer `--minimal` over `--bare` because bare has a specific meaning in Git. Git is more or less part of niv's domain.
