### ISSUE TITLE
niv init: allow customising owner/repo/branch/revision of nixpkgs

### ISSUE THREAD

**Issue by adrian-gierakowski** [nmattia/niv#192]
I'd like to be able to initialise a `niv` based project with specific version of `nixpkgs`

currently I need to wait for `niv init` to prefetch whatever version of `nixpkgs` it's got hardcoded and then remove it and add the one I want to use

**Comment by nmattia** [comment]
Agreed, I've been annoyed by this a few times already.

**Comment by emilazy** [comment]
Note that the `nixpkgs-channel` repo being used by default currently has been deprecated in favour of `nixpkgs` proper (should this be a separate issue?)

**Comment by nmattia** [comment]
No, it's fine to track this here. I'm really snowed under until Friday, I'm hoping to get some time then to work on this.

**Comment by rpearce** [comment]
> Note that the nixpkgs-channel repo being used by default currently has been deprecated in favour of nixpkgs proper...

@emilazy Please forgive me for making noise here – can you help guide me on how I can find out more about this?

**Comment by emilazy** [comment]
Hm, I distinctly remember it being in the nixpkgs-channels repo description, but it doesn't seem to be there. Either I'm misremembering where it was, or maybe it was changed? The upstream nixpkgs repo has the same branches as nixpkgs-channels now, but I agree a canonical answer about which repo should be used would be nice. I'll update this post if I can find anything more concrete.

**Comment by adrian-gierakowski** [comment]
@rpearce have a look here: https://github.com/NixOS/nixpkgs/issues/71176

**Comment by adrian-gierakowski** [comment]
Closing as this seems to be covered by #239 

Thanks @nmattia!
