### ISSUE TITLE
Get emacs packages using niv

### ISSUE THREAD

**Issue by analyticd** [nmattia/niv#196]
Perhaps this is already possible, but it doesn't seem so. 

Be able to do something like

`niv add cute-jumper/org-table-sticky-header`

and then in an emacs/default.nix, analogous to vim/default.nix, do 

`org-table-sticky-header = pkgs.callPackage epkgs.sources.org-table-sticky-header`.

**Comment by nmattia** [comment]
I'm not quite sure how the emacs infrastructure works. For vim, [I call `buildVimPlugin` on the source from niv](https://github.com/nmattia/homies/blob/adcae33c1a9065922fcd17a4769a0f9d118b1dc8/vim/default.nix#L50-L55): 

``` nix
  extraPackages = with vimPlugins;
    [
      ctrlp
      ...
      youcompleteme
      (vimUtils.buildVimPlugin
        { name = "vim-terraform";
          src = sources.vim-terraform;
          buildPhase = ":";
        }
      )
    ]
```

maybe you can do something similar?

**Comment by analyticd** [comment]
Thanks for your response. I'll see what I can come up with.
