### ISSUE TITLE
Provide a way to override sources with local checkouts

### ISSUE THREAD

**Issue by disassembler** [nmattia/niv#197]
It would be nice to have an upstream way of overriding at build time a niv source with a local checkout. We forked niv a while ago to do this using `NIX_PATH` to override sources, but it's a bit of a pain maintaining our fork. I'd like to open the discussion for how this could be done in a way that @nmattia would support upstream.

**Comment by zimbatm** [comment]
This reminds me of [`npm link`](https://docs.npmjs.com/cli/link) which allows to override a package with a local dependency during development. One important attribute is that the link is transparent and it's not possible to commit the link by mistake. At the moment you can override the sources.nix manually but then it adds a dirty file to the repository.

**Comment by kolloch** [comment]
@zimbatm How does it prevent the file from being submitted? A pre-commit hook searching for a certain keyword?

**Comment by zimbatm** [comment]
I think it's replacing the `node_modules/<package>` with a symlink to the project. Generally the node_modules folder is `.gitignored`. Basically you want a second file that contains the overrides and which is stored out of tree or gitignored.

**Comment by nomeata** [comment]
I could also imagine `NIV_name = path-to-local-checkout`

**Comment by nomeata** [comment]
In one of my projects I have this little code
```
 let foo-src =
   let env = builtins.getEnv "FOO_SRC"; in
   if env != "" then env else nixpkgs.sources.foo; in
```
moving this into the default `sources.nix` would solve this quite neatly, wouldn't it?

**Comment by nmattia** [comment]
Let's discuss everything here: https://github.com/nmattia/niv/issues/31

**Comment by nmattia** [comment]
For the record: with https://github.com/nmattia/niv/pull/260 you can name `export NIV_OVERRIDE_foo_bar=baz` for replacing `foo-bar` with the path `baz`.

**Comment by asheshambasta** [comment]
My apologies for bringing this back up, but `NIV_OVERRIDE_foo` seems to be confusing Nix for me. 
I've tried:
```
╭─ashesh@quasar-nixos-tr ~/code/asheshambasta/reflex-frp/projects/flowerpower ‹showcase/servant-reflex-dependency*›
╰─$ export NIV_OVERRIDE_prelude_polysemy=/home/ashesh/code/asheshambasta/prelude-polysemy

```
Which gives: 
```
╭─ashesh@quasar-nixos-tr ~/code/asheshambasta/reflex-frp/projects/flowerpower ‹showcase/servant-reflex-dependency*›
╰─$ nix-shell --run 'cabal new-repl fht-data -v3'                               these derivations will be built:
  /nix/store/pknldnghs3jpm92h34yp0fxl722ghwhy-prelude-polysemy-0.1.0.0.drv
  /nix/store/p15hqc48ky4vk54b3h6rj3n04ygjrnaa-ghc-8.6.5-with-packages.drv
building '/nix/store/pknldnghs3jpm92h34yp0fxl722ghwhy-prelude-polysemy-0.1.0.0.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/3ybbc3vag4mpwaqglpdac4v413na3vhl-ghc-8.6.5.
unpacking sources
unpacking source archive /home/ashesh/code/asheshambasta/prelude-polysemy/prelude-polysemy.cabal
do not know how to unpack source archive /home/ashesh/code/asheshambasta/prelude-polysemy/prelude-polysemy.cabal
builder for '/nix/store/pknldnghs3jpm92h34yp0fxl722ghwhy-prelude-polysemy-0.1.0.0.drv' failed with exit code 1
cannot build derivation '/nix/store/p15hqc48ky4vk54b3h6rj3n04ygjrnaa-ghc-8.6.5-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/p15hqc48ky4vk54b3h6rj3n04ygjrnaa-ghc-8.6.5-with-packages.drv' failed
```

In the package depending on `prelude-polysemy`, I'm attempting to call `callCabal2nix` on `(import sources.nix).prelude-polysemy`. 

This is with `0.2.13`.

**Comment by nmattia** [comment]
Hey @asheshambasta , do you have some code I could play with? Maybe a link to a repo/branch?

**Comment by asheshambasta** [comment]
@nmattia Hi! Thanks for taking the time to look into this. The problem code is https://github.com/asheshambasta/flowerpower/commit/0dcb40e87d35fe94f27f5d6d8db764ec05abe029#diff-245563af9e34754739b12b294f3324c1d42c116ace7ce8735e21dfbc82d8e064R38-R39.

**Comment by nmattia** [comment]
Hi, I gave this a try and it appears to work...
 
I've checked out the commit you linked above, and changed the `default.nix` to this:

``` nix
{ system ? builtins.currentSystem }:
let
  sources = import ./nix/sources.nix;
  pkgs = import sources.nixpkgs {};
in

  pkgs.haskellPackages.callCabal2nix "prelude-polysemy" sources.prelude-polysemy {}
```

Then I checked out https://github.com/asheshambasta/prelude-polysemy to `./prelude-polysemy`, and ran this:

>  NIV_OVERRIDE_prelude_polysemy="$PWD/prelude-polysemy/" nix-build

and the library started building (failed after a while due to compilation error). I get the same behavior if I leave out the `NIV_OVERRIDE_prelude_polysemy` (except that the library actually compiles, but for the problem at hand that's irrelevant).

What's the content of `/home/ashesh/code/asheshambasta/prelude-polysemy`?

**Comment by asheshambasta** [comment]
@nmattia Hi, I'll give your suggestion a try. 


> What's the content of `/home/ashesh/code/asheshambasta/prelude-polysemy`?
```
cabal.project.local
CHANGELOG.md
default.nix
dist
dist-newstyle
LICENSE
nix
overlay.nix
prelude-polysemy.cabal
release.nix
shell.nix
src
TAGS

```

**Comment by asheshambasta** [comment]
So it seems like this is an issue with my particular nix setup. Since this is a Reflex-FRP project, I'm using reflex-platform; which suggests a particular structure of default.nix, which is what I've done so far. 
Given that in your case, the override works as expected is quite confusing to me. I seem to consistently get: 
```
╰─$ export NIV_OVERRIDE_dbstorage_polysemy="/home/ashesh/code/asheshambasta/dbstorage-polysemy"
╭─ashesh@quasar-nixos-tr ~/code/asheshambasta/reflex-frp/projects/flowerpower ‹showcase/servant-reflex-dependency*›
╰─$ nix-shell --run ./HotBackend.sh
these derivations will be built:
  /nix/store/3ps9bzcr39zm72ylgixp69iywvy017ks-dbstorage-polysemy-0.1.0.0.drv
  /nix/store/3c8iahf0xq6jpwm6jsyjmfanirrzwl89-ghc-8.6.5-with-packages.drv
building '/nix/store/3ps9bzcr39zm72ylgixp69iywvy017ks-dbstorage-polysemy-0.1.0.0.drv'...
setupCompilerEnvironmentPhase
Build with /nix/store/3ybbc3vag4mpwaqglpdac4v413na3vhl-ghc-8.6.5.
unpacking sources
unpacking source archive /home/ashesh/code/asheshambasta/dbstorage-polysemy
do not know how to unpack source archive /home/ashesh/code/asheshambasta/dbstorage-polysemy
builder for '/nix/store/3ps9bzcr39zm72ylgixp69iywvy017ks-dbstorage-polysemy-0.1.0.0.drv' failed with exit code 1
cannot build derivation '/nix/store/3c8iahf0xq6jpwm6jsyjmfanirrzwl89-ghc-8.6.5-with-packages.drv': 1 dependencies couldn't be built
error: build of '/nix/store/3c8iahf0xq6jpwm6jsyjmfanirrzwl89-ghc-8.6.5-with-packages.drv' failed
```
