### ISSUE TITLE
compare with nix-update-source?

### ISSUE THREAD

**Issue by timbertson** [nmattia/niv#20]
Hello, I just found out about about `niv` through the latest NixOS weekly. I maintain [nix-update-source](https://github.com/timbertson/nix-update-source). I figure it's worth figuring out where you might prefer one or the other? (and maybe sharing/stealing some ideas ;))

From a quick skim, I'd summarize the difference as: niv is a CLI for adding/managing dependencies explicitly, creating a couple of self-contained files (sources.nix + json) which fetch the deps.
nix-update-source is more of a template-based system for updating sources without repeating yourself when updating packages, creating either a JSON file per dependency (importable via an API in nixpkgs itself) or in a "zero runtime" mode which updates nix expressions inline.

Initial thoughts on bringing the two ideas closer together (if we want to) would be adding an `init`-like action to nix-update-source, and on the other hand adding support for storing templates in the generated source of `niv` (so you don't have to specify them on the command line each time).

I also maintain [nix-pin](https://github.com/timbertson/nix-pin) which is vaguely related, but is more for development setup (easily building local versions of multiple packages).

**Comment by nmattia** [comment]
Forgot to update this ticket! We had a chat with @timbertson and @zimbatm about nix-path, nix-update-source and niv about two weeks ago.

@timbertson wrote up some of the ideas exchanged then: https://github.com/timbertson/nix-source-automation

Thanks for reaching out!
