### ISSUE TITLE
`niv update nixpkgs` doesn't update nixpkgs

### ISSUE THREAD

**Issue by kolloch** [nmattia/niv#200]
<pre><font color="#5FD700">❯</font> niv show nixpkgs
<font color="#EEEEEC"><b>nixpkgs</b></font>
  homepage: https://github.com/NixOS/nixpkgs
  url: https://github.com/NixOS/nixpkgs-channels/archive/8130f3c1c2bb0e533b5e150c39911d6e61dcecc2.tar.gz
  owner: NixOS
  branch: nixos-unstable
  url_template: https://github.com/&lt;owner&gt;/&lt;repo&gt;/archive/&lt;rev&gt;.tar.gz
  repo: nixpkgs-channels
  type: tarball
  sha256: 154nrhmm3dk5kmga2w5f7a2l6j79dvizrg4wzbrcwlbvdvapdgkb
  description: A read-only mirror of NixOS/nixpkgs tracking the released channels. Send issues and PRs to
  rev: 8130f3c1c2bb0e533b5e150c39911d6e61dcecc2
</pre>

<pre><font color="#5FD700">❯</font> niv update nixpkgs
<font color="#EEEEEC"><b>Update nixpkgs</b></font>
<font color="#5AA40F"><b>Done</b></font>: Update nixpkgs
</pre>

<pre><font color="#5FD700">❯</font> niv show nixpkgs  
</pre>

=> output is unchanged

Note that this works for me for other github sources and `niv update` without `nixpkgs` also updates `nixpkgs`.

**Comment by nmattia** [comment]
Hey @kolloch ! I've been hit by that in the past. By "that", I mean nixpkgs updating less quickly that I'd hope :) https://github.com/NixOS/nixpkgs/tree/nixos-unstable

**Comment by kolloch** [comment]
Oh, right `niv update` also doesn't do stuff. Sorry for that.

**Comment by nmattia** [comment]
> also doesn't do stuff.

What do you mean? 

> Sorry for that.

Don't worry!
