### ISSUE TITLE
Specify `name` for fetchTarballs

### ISSUE THREAD

**Issue by emilazy** [nmattia/niv#211]
Not sure if this is done already with other fetchers, so I'm only reporting this most restricted version, but ending up with a bunch of undifferentiated `*-source`s in the store can be pretty confusing. `builtins.fetchTarball` actually does support [passing a `name`](https://github.com/NixOS/nix/blob/aef635d/src/libexpr/primops.cc#L2057-L2067), though it's undocumented.

**Comment by nmattia** [comment]
That's a great idea! I didn't know about it. I'll get started.
