### ISSUE TITLE
niv add --sources-file does not work

### ISSUE THREAD

**Issue by shmish111** [nmattia/niv#243]
I want to use niv with a different sources location which I can do with `niv init -s ./nix/other-sources.json` however I can't then specify this alternative sources for `niv add` (and in the future `niv update`).

**Comment by nmattia** [comment]
I think `--sources-file` is a global option; I'm actually surprised `niv init -s ...` works. Can you try specifying `-s` _before_ the command, i.e. just after the exe name? `niv -s foobar.json add ...`

**Comment by nmattia** [comment]
Closing for now, feel free to re-open if this is still a problem.
