### ISSUE TITLE
No longer works in Github CI

### ISSUE THREAD

**Issue by anka-213** [nmattia/niv#280]
Five days ago something changed. I'm not sure what:
https://github.com/nix-dot-dev/getting-started-nix-template/actions?query=workflow%3A%22Update+niv%22

Now we're getting error messages like this:

```
  Package: gitignore.nix
  FATAL: Cannot get latest revision for branch 'master' (hercules-ci/gitignore.nix)
  The request failed: Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("server","GitHub.com"),("date","Fri, 11 Sep 2020 08:12:48 GMT"),("content-type","application/json; charset=utf-8"),("status","404 Not Found"),("x-github-media-type","github.v3; param=sha"),("access-control-expose-headers","ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset"),("access-control-allow-origin","*"),("strict-transport-security","max-age=31536000; includeSubdomains; preload"),("x-frame-options","deny"),("x-content-type-options","nosniff"),("x-xss-protection","1; mode=block"),("referrer-policy","origin-when-cross-origin, strict-origin-when-cross-origin"),("content-security-policy","default-src 'none'"),("vary","Accept-Encoding, Accept, X-Requested-With"),("content-encoding","gzip"),("X-Ratelimit-Limit","60"),("X-Ratelimit-Remaining","57"),("X-Ratelimit-Reset","1599815568"),("X-Ratelimit-Used","3"),("Content-Length","91"),("X-GitHub-Request-Id","07C0:4303:4B774F:83C930:5F5B3180")], responseBody = "{\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest\"}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
  NOTE: You may want to retry with an authentication token:
  
      GITHUB_TOKEN=... niv <cmd>
  
  For more information on rate-limiting, see
  
      https://developer.github.com/v3/#rate-limiting
  
  
  FATAL: One or more packages failed to update:
```

Adding a GITHUB_TOKEN doesn't help.

Do you have any idea what the problem is?

**Comment by anka-213** [comment]
@domenkozar I opened an issue for it here instead of in your `getting-started-nix-template` repo, since I assumed it's an upstream issue. Is this correct?

**Comment by domenkozar** [comment]
I've been seeing this too, no idea yet what's going on.

**Comment by nmattia** [comment]
I think GitHub might have started using `GITHUB_PATH`, which is read by `niv` (and prepended to the HTTP path used when making API calls). Will need to investigate.

**Comment by dhess** [comment]
Same here.

**Comment by nmattia** [comment]
Can somebody try `echo`ing or `unset`ing `GITHUB_PATH`? I don't have a GitHub action workflow handy

**Comment by domenkozar** [comment]
Can confirm unsetting `GITHUB_PATH` makes it work again.

**Comment by domenkozar** [comment]
https://github.com/nix-dot-dev/getting-started-nix-template/pull/16

**Comment by nmattia** [comment]
Great, I'll work on the workaround.

**Comment by dhess** [comment]
@domenkozar It's a bit off-topic, but how do you test GitHub Actions? I don't know of a way to run them manually unless they've failed, and when you re-run those, it appears to use the same revision of the action that failed the first time, not any newer revision.

**Comment by nmattia** [comment]
@domenkozar mind having a quick look here, see if that makes sense? https://github.com/nmattia/niv/pull/281

**Comment by nmattia** [comment]
I've [just release v0.2.18](https://github.com/nmattia/niv/releases/tag/v0.2.18), feel free to re-open if the workaround is not applicable or if the problem persist!

**Comment by anka-213** [comment]
@dhess The solution I used was to add "on: push" to the yaml file, so it runs every time you push new changes.

**Comment by dhess** [comment]
@anka-213 Ahh, that's clever, thanks!

**Comment by anka-213** [comment]
Hmm, I've not gotten it to work yet. Neither unsetting  GITHUB_TOKEN nor upgrading to latest version of niv helped for me. https://github.com/anka-213/cclaw-nix-stuff/actions?query=workflow%3A%22Update+niv%22

and I don't see any succeeding tests here either: https://github.com/nix-dot-dev/getting-started-nix-template/actions?query=workflow%3A%22Update+niv%22

**Comment by dhess** [comment]
Same, my GitHub Actions using niv are still failing after upgrading to this version of niv.

**Comment by nmattia** [comment]
> Neither unsetting GITHUB_TOKEN

I think you mean `GITHUB_PATH`? 

> nor upgrading to latest version of niv helped for me. 

How exactly are you pinning the version? Have you tried building from master (using the cache) like [niv-updater-action](https://github.com/knl/niv-updater-action/blob/279ea9b4f5152bdbc0ae240fc894e7f371b62a5f/niv-updater#L41-L43)? That one (niv-updater-action) is now running smoothly again.

**Comment by dhess** [comment]
Oh, do we still need to unset `GITHUB_PATH` to make this work with GitHub Actions?

**Comment by nmattia** [comment]
No, it should work out of the box with niv 0.2.18. Are you sure you're using that version?

**Comment by dhess** [comment]
I pinned the latest version in my `sources.json`, but didn't make it available in the shell in which the GitHub Action was running. Sorry, user error! Should be fixed now.
