### ISSUE TITLE
Update doesn't work with custom (non-github) resources

### ISSUE THREAD

**Issue by jpotier** [nmattia/niv#326]
I host some projects on my personal instance of Gitea, and I cannot use:

```
$ niv add overlays-personal -v master -t 'https://git.marvid.fr/mpo/overlays-personal/archive/<version>.tar.gz'
$ #… some weeks later
$ niv update overlays-personal
```

This command succeeds, but does not update to the latest commit of the master branch. I've also tried

```
$ niv update overlays-personal -v master
```

as indicated in the README for the ghc custom URL example, but that doesn't work either.

At the moment, I need to do the following to force an update (the equivalent of “turning it off and on again”):

```
$ niv drop overlays-personal
$ niv add overlays-personal \
    -v master \
    -t 'https://git.marvid.fr/mpo/overlays-personal/archive/<version>.tar.gz'
```

Why is it not updating? Am I doing something wrong?

**Comment by nmattia** [comment]
The resolved URL (`https://git.marvid.fr/mpo/overlays-personal/archive/master.tar.gz`) does not change so `niv` does not expect the content (and hence the `sha256`) to change. If `git.marvid.fr/mpo/overlays-personal` is a git repo, I suggest you use `niv add git` (see the "experimental commands" here: https://github.com/nmattia/niv#add)

**Comment by jpotier** [comment]
> The resolved URL (`https://git.marvid.fr/mpo/overlays-personal/archive/master.tar.gz`) does not change so `niv` does not expect the content (and hence the `sha256`) to change. If `git.marvid.fr/mpo/overlays-personal` is a git repo, I suggest you use `niv add git` (see the "experimental commands" here: https://github.com/nmattia/niv#add)

It is a git repo, I'll try that, thanks!
