### ISSUE TITLE
`nix-env -iA nixpkgs.niv` fails with Base64 error on MacOS Catalina

### ISSUE THREAD

**Issue by tysonzero** [nmattia/niv#338]
```
installing 'niv-0.2.18'
these paths will be fetched (1.55 MiB download, 9.18 MiB unpacked):
  /nix/store/9ahal9yxf9ay4zzxan63n0k5z58lsidb-niv-0.2.18-data
  /nix/store/vysxi8m9mnd2r3vix21kq4k23hyc96wr-niv-0.2.18-bin
  /nix/store/wx6gly6zfy4wz564qcx188n0g672xz5w-niv-0.2.18
error: invalid character in Base64 string
```

**Comment by nmattia** [comment]
This looks like an actual "nix" issue. Is that the whole output you get? What exact command are you running, and what's your `nix --version`?

**Comment by tysonzero** [comment]
That was the full output from `nix-env -iA nixpkgs.niv`

`nix --version` was `nix (Nix) 2.3.10`

Trying to reproduce it now just gives me:

```
copying path '/nix/store/9ahal9yxf9ay4zzxan63n0k5z58lsidb-niv-0.2.18-data' from 'https://cache.nixos.org'...
copying path '/nix/store/vysxi8m9mnd2r3vix21kq4k23hyc96wr-niv-0.2.18-bin' from 'https://cache.nixos.org'...
copying path '/nix/store/wx6gly6zfy4wz564qcx188n0g672xz5w-niv-0.2.18' from 'https://cache.nixos.org'...
```

So it seems like my precise configuration may have been added to the nixos cache in the last couple days. Although I'd wager that without the cache it would have probably failed again.

**Comment by nmattia** [comment]
Right, however it looks like a Nix error, as opposed to a build error (notice that it started no build). All files were present in the cache already, most likely it was the download that was failing. I'm gonna close for now, feel free to re-open if you run into a similar issue again.
