### ISSUE TITLE
Use install-nix-action and cachix-action

### ISSUE THREAD

**Issue by domenkozar** [nmattia/niv#340]
Hey @nmattia,

It's been a while since we talked about this!

I was looking at niv today and noticed you're still using your own actions - to avoid maintenance I'd suggest to use the two actions I maintain for the community. They have evolved quite a bit!

If there's something missing I'm happy to improve them further :)

**Comment by nmattia** [comment]
It was [brought to my attention](https://github.com/nix-community/naersk/pull/209#issuecomment-975844003) that indeed they had evolved a fair bit. PRs very welcome :)
