### ISSUE TITLE
Bug while niv update

### ISSUE THREAD

**Issue by shd101wyy** [nmattia/niv#346]
$ niv update nixpkgs -b nixos-21.11
Update nixpkgs
  FATAL: Could not read the output of 'nix-prefetch-url'. This is a bug. Please create a
  ticket:
  
    https://github.com/nmattia/niv/issues/new
  
  Thanks! I'll buy you a beer.
  command: 
  nix-prefetch-url--unpack https://github.com/NixOS/nixpkgs/archive/2128d0aa28edef51fd8fef38b132ffc0155595df.tar.gz --name 2128d0aa28edef51fd8fef38b132ffc0155595df.tar.gz
  stdout: 
  
  stderr: 
  nix-prefetch-url: /nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31/lib/libc.so.6: version `GLIBC_2.33' not found (required by /nix/store/l6mx3ksrzf7pnw0jyaalmg6kcwhb5gz3-sqlite-3.36.0/lib/libsqlite3.so.0)
  
  FATAL: One or more packages failed to update:
  nixpkgs: ExitFailure 1
ERROR: ExitFailure 1

**Comment by nmattia** [comment]
Hi, looks like a glibc mismatch. What happens if you run the `nix-prefetch-url` command on its own?

**Comment by shd101wyy** [comment]
It seems to be working after I upgrade the nixpkgs version :+1:
