### ISSUE TITLE
feature request: force update

### ISSUE THREAD

**Issue by yshui** [nmattia/niv#388]
Some urls used in nix will have different contents overtime, for example: `https://static.rust-lang.org/dist/channel-rust-nightly.toml` used by the fenix rust overlay to fetch manifests; or `https://code.visualstudio.com/sha/download?build=insider&os=linux-x64`, which is suggested [here](https://nixos.wiki/wiki/Visual_Studio_Code#Insiders_Build) for fetching insider builds of vscode.

What I observed is, `niv update` does nothing for those urls. Is it because their url is fixed? If so, can `niv update` have an option to update of the `sha256`s regardless if the urls are unchanged?

**Comment by nmattia** [comment]
Yes that's right! Let's continue the discussion here: https://github.com/nmattia/niv/issues/240
