### ISSUE TITLE
GitHub Enterprise and custom hostname support

### ISSUE THREAD

**Issue by nmattia** [nmattia/niv#56]
It would be nice to support custom hostnames.

We already use something similar in the tests: https://github.com/nmattia/niv/blob/5d9e3a5f7d51765f0369a4682770ec57d863f19f/tests/default.nix#L24-L27

A few thoughts:

* The [hub](https://hub.github.com/hub.1.html) command line tool uses the `GITHUB_HOST` environment variable. However in our case we'd probably want to store the hostname in the `sources.json`: it's not unlikely for someone to use a custom github deployment _and_ also open source packages.
* The [github](http://hackage.haskell.org/package/github-0.21/docs/src/GitHub.Request.html#executeRequestWithMgr%27) library seems to use the host name directly when communicating with the API. This seems to be at odds with the [GitHub Enterprise documentation](https://developer.github.com/enterprise/2.15/v3/) which stipulates that the API should be reached at `http(s)://[hostname]/api/v3`. We can't ask for `[hostname]/api/v3` to be passed as `GITHUB_HOST` because we'll use the raw (`[hostname]`) hostname for creating the URL. CC @phadej
* Unlike the `GITHUB_HOST` we _do not_ want to store the `GITHUB_TOKEN` in the sources.json. Either we don't allow the user to use multiple tokens, or we ask the user to issue a `niv update <package>` for each package hosted on a custom GitHub deployment. Alternatively we go crazy and allow the user to either (1) map a specific environment variable per token (e.g. `GITHUB_TOKEN_[PACKAGE]`) or we (2) ask the user to specify a _command_ in the sources.json which will return the token (e.g. `pass my-github-token-for-package`).

CC @nlewo

**Comment by phadej** [comment]
If someone needs something fixed for Enterprise stuff, they are welcome to make a PR.

That is the part I cannot develop or test (and honestly not even very interested in to, as a spare-time OSS maintainer)
