### ISSUE TITLE
Not installing niv?

### ISSUE THREAD

**Issue by roberth** [nmattia/niv#57]
We've had a situation where two or more versions of niv were in use. They come from
 - Alice's profile (`nix-env -i` as recommended)
 - Bob's profile
 - the project (`shell.nix`)

Two first two will never be consistent, so it seems best to rely on the second, but that creates a problem with bootstrapping. So I figured that to run `niv init` without installing, I could run
```
nix run -f https://github.com/nmattia/niv/tarball/master niv -c niv init
```
So, is this a method that should be recommended?
If so, it would be nice to reintroduce a default `shell.nix`, optionally, so you'd have:
```
$ nix run -f https://github.com/nmattia/niv/tarball/master niv -c niv init --scaffold
$ nix-shell
[nix-shell]$ niv add foo/bar
```

**Comment by dejanr** [comment]
I was looking for similar issue and found this exact concern. Also that niv init is still not part of nixpkgs is making it harder for new installs, and having better adoption.
In my opinion i think only niv init should be part of global nixpkgs, for bootstrapping new projects, and niv commands should be only accessible from inside the nix shell? 

So end goal user experience could be:

- For new project:

```
nix-env -iA nixpkgs.niv-init // or it could be part of your nixos configuration
niv-init new-project
cd new-project
nix-shell .
niv ...
```

- For existing project

```
cd new-project
nix-shell
niv ...
```

**Comment by nmattia** [comment]
I like both approaches. Another one that we may consider is to simply have a `niv-init` shell alias that does nothing but pull the latest `sources.nix` and `sources.json` from the repo. @roberth raises another issue with `--scaffold`: people have been complaining that `niv` _doesn't provide scaffolding anymore_, e.g. it only creates the `sources.*` files.

I'm tempted to have another scaffolding tool that'll create some `default.nix`, `shell.nix`, etc, and potentially provide some scaffolding for `niv` as well.

**Comment by roberth** [comment]
@nmattia I'd love to see a scaffolding tool that uses the module system for describing templates! Just saying ;)

**Comment by nmattia** [comment]
Re. upstreaming `niv` to nixpkgs: it’s happening, just merged a branch setting everything up for a hackage release. Unfortunately I forgot my hackage password, so the _actual_ release will have to wait a day or two.

@roberth can you clarify what you mean by “using the module system for describing templates”?

**Comment by nmattia** [comment]
niv is now in nixpkgs (see README). Feel free to continue the `--scaffold` discussion [here](https://github.com/nmattia/niv/issues/95).
