### ISSUE TITLE
Separate `update` and `modify` commands?

### ISSUE THREAD

**Issue by michaelpj** [nmattia/niv#63]
At the moment `update` handles both changing attributes *and* updating the rev from the upstream repository.

You might well want to do these separately, e.g. change the tracking branch but don't update *right now*.

Perhaps separate `niv update` and `niv modify` commands would make sense.

**Comment by nmattia** [comment]
I was thinking about something slightly different, e.g. the ability of "blocking" certain attributes. You'd say `niv block <package> rev` and `rev` would never get updated. But blocking a single attribute is a bit silly so maybe `niv block <package>` makes more sense. What's the use case for changing the tracked branch but not updating the package?

**Comment by michaelpj** [comment]
I'm thinking of something like:
- You're working on a big shared repo
- You've realised you need to track a different branch of a dep, e.g. the stable one instead of master
- You want to commit this knowledge so other people don't update along the wrong branch
- But you don't want to actually update the dep because that might break things etc.

**Comment by michaelpj** [comment]
I think that workflow would be quite awkward with `niv block`.

**Comment by nmattia** [comment]
Turns out I'm loving this idea more and more.
