### ISSUE TITLE
Some error cases silently do nothing

### ISSUE THREAD

**Issue by michaelpj** [nmattia/niv#65]
In particular, there are a number of cases where we expect a JSON object to be of a particular type, and if isn't we do nothing - we should probably fail noisily instead.

**Comment by nmattia** [comment]
I tried to make sure we fail as little as possible, though it should definitely emit a warning. Happy to reconsider all of this.

**Comment by michaelpj** [comment]
Yeah, I think many should be warnings at most, but the JSON type mismatch means you have a malformed file, which I definitely want to know about as a user.

**Comment by nmattia** [comment]
Was fixed in #68 . It now just fails :)
