### ISSUE TITLE
Update packages with common attribute values

### ISSUE THREAD

**Issue by nlewo** [nmattia/niv#80]
It would be nice to be able to update a set of dependency as a whole. For instance, update all Docker images with tag latest. Another example is currently implemented in the nixpkgs-tungsten repository https://github.com/cloudwatt/nixpkgs-tungsten/blob/master/tools/sources.sh: several repositories with identical branches have to be fetched to build the project. It’d be nice to be able to only update all identical branches (targeting the same release).

The idea is to add a `match` option on the `update` and `drop` commands. The match option takes a key value pair. The update command only updates dependencies matching the pair.
Usage example

```
niv update [<name>] [--match <KEY=VALUE>] [--attribute <KEY=VALUE>]

# To update all docker images with a tag latest
niv update --match type=docker --match tag=latest
niv update nixpkgs
```

Note this could also be useful for drop and show commands.
```
niv drop [<name>] [--match <KEY=VALUE>]
    
niv drop --match type=docker
```

**Comment by andir** [comment]
This sounds like a nice idea but probably not a good fit for niv.
