### ISSUE TITLE
Niv bisect, niv diff, niv <some-op-on-source>

### ISSUE THREAD

**Issue by nmattia** [nmattia/niv#96]
Similar to #69 

Niv actually has access to a lot of information. It could compare new and old `rev`s to provided changelog changes (#69 ), diff the sources, or even run some actions on all the revs between `rev0` and `rev1` (similar to git bisect).

**Comment by mweinelt** [comment]
Kernel have a non-booting kernel since the v20.03 upgrade and through the niv/morph stack I'm currently unable to bisect this easily. So having a bisect feature would be awesome.

**Comment by andir** [comment]
Why not just `git-bisect(1)` on your repo? That wont go through remote revisions but this feels like feature creep.

**Comment by refnil** [comment]
@andir I could be mistaken but maybe the idea was to bisect across dependencies.

Let's say you depend on 3 projects. You update all of them to a new version and then you project does not build anymore.
 The `niv bisect` command would help solve this situation by bisecting on the revs of those dependencies instead your own project like git bisect does.

**Comment by gilligan** [comment]
@refnil you might be right about that! 

However we need to be careful about not turning niv into some swiss army knife for “all things dependencies” and focus on main functionality around adding/updating/modifying dependencies.
